name: Pull
on: 
  pull_request:
    branches:
      - '*'
jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps: 
      - name: Branch Name Check
        run: node ./tools/branchCheckName